### PR TITLE
Solution For Valid Soduku Problem

### PR DESCRIPTION
**Pull request by yash13902**
Program to check if soduku is valid or not.
Please accept my pull request, Thank You!

### CODE REVIEW

**Comment by dikshantrajput** [comment]
Edit the PR title please

**Comment by yash13902** [comment]
I have changed the PR title.
Thank You!

**Comment by dikshantrajput** [comment]
@yash13902  Add your name in the contributors.html file. Everything else is good

**Review by dikshantrajput — APPROVED** [review]

**Comment by yash13902** [comment]
I have added my name in the contributors.html
Thank You!

**Pull request merged**
