### PR TITLE
Adding python code

### PR DESCRIPTION
**Pull request by Danuragtiwari**
Added file in python folder
Added name in contribution file

### CODE REVIEW

**Comment by Danuragtiwari** [comment]
@maheshjainckd  review it please!

**Comment by Danuragtiwari** [comment]
@maheshjainckd check it once

**Comment by dikshantrajput** [comment]
Rename the PR title please

**Comment by Danuragtiwari** [comment]
@dikshantrajput is it fine?

**Comment by Danuragtiwari** [comment]
@dikshantrajput please check it once!

**Pull request closed without merging**
